### ISSUE TITLE
Blue Force Tracker issues

### ISSUE THREAD

**Issue by lubomirblazekcz** [KoffeinFlummi/AGM#1170]
Don't know if it's still actual, but in 0.93 the Blue Force Tracker module doesn't work without problems.

On dedicated server I had these kind of problems.
- [ ] When re-connecting to the mission, the markers are no more on the map
- [x] When respawning, the marker of the group you we're in is not on the map anymore
- [x] Not sure about this one, but when someone change the group, or create new group the marker is not on the map
