### ISSUE TITLE
Medical Rewrite

### ISSUE THREAD

**Issue by KoffeinFlummi** [KoffeinFlummi/AGM#1224]
Oh boy, here goes...
#### Reason

Medical has been changed extensively over the months and has grown slightly frankensteinian.
#### Objectives

moved to #1491.

---

Still needs to be done:
- [x] Tweak fall damage (#812) - **working in SP**
- [x] Basic AI support (#856)
- [x] Treatment inside vehicles (#716)
- [x] Random death with max unconscioussness time (#1550, #1572) - **working in SP**
- [x] Test damage tetris.
- [x] Loading into vehicles in MP
- [x] test: does waking up always restore the animation? (HSV yesterday)
- [x] test: medevac in mp
