### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by KoffeinFlummi** [KoffeinFlummi/AGM#212]
All the random stuff needed for a release.
- [x] Double check all stringtables (#249)
- [x] Change version numbers (CfgPatches, mod.cpp...)
- [ ] Update PBO overview
- [ ] Update feature list
