### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by KoffeinFlummi** [KoffeinFlummi/AGM#804]
- [x] doublecheck version numbers
- [x] INCLUDE THE SERVER KEY THIS TIME
- [x] write changelog
- [ ] write documentation
- [x] rename folders to lowercase
- [x] exclude disposable, getin
- [x] ...
- [x] profit.
